export type RootStackParamList = {
    Splash: undefined;
    Onboarding: undefined;
    Login: undefined;
    Signup: { role?: 'freelancer' | 'hiring' | 'requester' };
    OTPVerification: { email: string; flow: 'signup' | 'forgot'; name?: string; role?: 'freelancer' | 'hiring' | 'requester'; password?: string };
    ForgotPassword: undefined;
    ResetPassword: { email: string; otp: string };
    Home: undefined;
    Main: undefined;
    ProfileSetup: undefined;
    Chat: { id: string };
    JobDetail: { id: string };
    CreateJob: undefined;
    MyJobs: undefined;
    JobPreview: { title: string; description: string; budget: string; budgetType: string; deadline: string; category: string; location: string; isRemote: boolean };
    Applicants: { jobId: string };
    HireConfirm: { applicantId: string; jobId: string };
    FreelancerProfile: { id: string };
    /** In-app WebView for portfolio / external links */
    PortfolioWebView: { url: string; title?: string };
    Search: undefined;
    FilterModal: undefined;
    CreatePost: undefined;
    PostComments: { postId: string; postOwnerId: string; caption: string; userName: string; userAvatar?: string; likesCount: number };
    Settings: undefined;
    EditProfile: undefined;
    Referral: undefined;
    Ratings: undefined;
    Notifications: undefined;
    Help: undefined;
    Terms: undefined;
    Report: undefined;
    NewChat: undefined;
    MessageSettings: undefined;
    SearchMessages: undefined;
    Messages: undefined;
};
