export type RootStackParamList = {
    Splash: undefined;
    Onboarding: undefined;
    Login: undefined;
    Signup: { role?: 'freelancer' | 'hiring' | 'requester' };
    OTPVerification: { email: string; flow: 'signup' | 'forgot'; name?: string; role?: 'freelancer' | 'hiring' | 'requester' };
    ForgotPassword: undefined;
    ResetPassword: { email: string; otp: string };
    Home: undefined;
    Main: undefined;
    ProfileSetup: undefined;
    Chat: { id: string };
    JobDetail: { id: string };
    CreateJob: undefined;
    MyJobs: undefined;
    JobPreview: { job: any };
    Applicants: { jobId: string };
    HireConfirm: { applicantId: string; jobId: string };
    FreelancerProfile: { id: string };
    Search: undefined;
    FilterModal: undefined;
    CreatePost: undefined;
    Settings: undefined;
    Ratings: undefined;
    Notifications: undefined;
    Help: undefined;
    Terms: undefined;
    Report: undefined;
    NewChat: undefined;
    MessageSettings: undefined;
    SearchMessages: undefined;
    Messages: undefined;
};
